"""
NeuroCron Persona Models
AudienceGenome customer personas and segments
"""

import uuid
from typing import Optional, List
from sqlalchemy import String, Text, Integer, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base


class Persona(Base):
    """Customer persona generated by AudienceGenome"""
    
    __tablename__ = "personas"
    
    # Organization
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
    )
    
    # Basic info
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    age_range: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    occupation: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    income_level: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    location: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    bio: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Psychographic data (stored as JSON arrays)
    goals: Mapped[Optional[dict]] = mapped_column(JSONB, default=list)
    pain_points: Mapped[Optional[dict]] = mapped_column(JSONB, default=list)
    motivations: Mapped[Optional[dict]] = mapped_column(JSONB, default=list)
    objections: Mapped[Optional[dict]] = mapped_column(JSONB, default=list)
    preferred_channels: Mapped[Optional[dict]] = mapped_column(JSONB, default=list)
    buying_triggers: Mapped[Optional[dict]] = mapped_column(JSONB, default=list)
    content_preferences: Mapped[Optional[dict]] = mapped_column(JSONB, default=list)
    brand_affinity: Mapped[Optional[dict]] = mapped_column(JSONB, default=list)
    
    # Summary
    psychographic_profile: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Generation context
    generation_context: Mapped[Optional[dict]] = mapped_column(JSONB, default=dict)


class AudienceSegment(Base):
    """Audience segment for targeting"""
    
    __tablename__ = "audience_segments"
    
    # Organization
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
    )
    
    # Segment info
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Filtering criteria
    criteria: Mapped[Optional[dict]] = mapped_column(JSONB, default=dict)
    
    # Stats
    estimated_size: Mapped[int] = mapped_column(Integer, default=0)
    
    # Status
    is_active: Mapped[bool] = mapped_column(default=True)

