"""
NeuroCron Strategy Models
NeuroPlan strategies and BrainSpark ideas
"""

import uuid
from typing import Optional, List
from sqlalchemy import String, Text, Integer, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base


class MarketingStrategy(Base):
    """12-month marketing strategy generated by NeuroPlan"""
    
    __tablename__ = "marketing_strategies"
    
    # Organization
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
    )
    
    # Strategy basics
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    executive_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    vision: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    mission: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Quarterly plans (JSON array)
    quarterly_plans: Mapped[Optional[dict]] = mapped_column(JSONB, default=list)
    
    # Channel strategies (JSON array)
    channel_strategies: Mapped[Optional[dict]] = mapped_column(JSONB, default=list)
    
    # Positioning
    competitor_positioning: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    unique_selling_propositions: Mapped[Optional[dict]] = mapped_column(JSONB, default=list)
    
    # Messaging
    messaging_framework: Mapped[Optional[dict]] = mapped_column(JSONB, default=dict)
    
    # Metrics
    success_metrics: Mapped[Optional[dict]] = mapped_column(JSONB, default=list)
    risks_and_mitigations: Mapped[Optional[dict]] = mapped_column(JSONB, default=list)
    
    # Budget
    budget_range: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    total_budget_estimate: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    
    # Timeline
    timeline_months: Mapped[int] = mapped_column(Integer, default=12)
    
    # Generation context
    generation_input: Mapped[Optional[dict]] = mapped_column(JSONB, default=dict)
    
    # Status
    status: Mapped[str] = mapped_column(String(20), default="draft")  # draft, active, archived


class CreativeIdea(Base):
    """Creative marketing idea generated by BrainSpark"""
    
    __tablename__ = "creative_ideas"
    
    # Organization
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
    )
    
    # Optional strategy link
    strategy_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("marketing_strategies.id", ondelete="SET NULL"),
        nullable=True,
    )
    
    # Idea details
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    category: Mapped[str] = mapped_column(String(50), nullable=False)  # campaign, content, social, ad, pr, event
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    hook: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Execution details
    target_emotion: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    estimated_impact: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)  # high, medium, low
    difficulty: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)  # easy, medium, hard
    timeline: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    required_resources: Mapped[Optional[dict]] = mapped_column(JSONB, default=list)
    example_execution: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Status
    status: Mapped[str] = mapped_column(String(20), default="new")  # new, in_progress, implemented, archived
    is_favorite: Mapped[bool] = mapped_column(default=False)

