"""Add RevenueLink models

Revision ID: 0ed3b7608d3e
Revises: 251ce9b2e8fb
Create Date: 2025-11-30 18:44:13.485814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed3b7608d3e'
down_revision: Union[str, None] = '251ce9b2e8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_performance',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('touchpoints', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('roas', sa.Float(), nullable=False),
    sa.Column('cpa', sa.Float(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=False),
    sa.Column('attribution_model', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_channel_perf_org_period', 'channel_performance', ['organization_id', 'period_start'], unique=False)
    op.create_table('campaign_roi',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_spend', sa.Float(), nullable=False),
    sa.Column('revenue_first_touch', sa.Float(), nullable=False),
    sa.Column('revenue_last_touch', sa.Float(), nullable=False),
    sa.Column('revenue_linear', sa.Float(), nullable=False),
    sa.Column('revenue_data_driven', sa.Float(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('roi_first_touch', sa.Float(), nullable=False),
    sa.Column('roi_last_touch', sa.Float(), nullable=False),
    sa.Column('roi_linear', sa.Float(), nullable=False),
    sa.Column('roi_data_driven', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revenue_events',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=255), nullable=True),
    sa.Column('attributed_campaign_id', sa.UUID(), nullable=True),
    sa.Column('attribution_model', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attributed_campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_revenue_events_org_date', 'revenue_events', ['organization_id', 'occurred_at'], unique=False)
    op.create_table('touchpoint_records',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('visitor_id', sa.String(length=100), nullable=False),
    sa.Column('touchpoint_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('medium', sa.String(length=100), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('campaign_name', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('landing_page', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('journey_position', sa.Integer(), nullable=True),
    sa.Column('is_first_touch', sa.Boolean(), nullable=False),
    sa.Column('is_last_touch', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_touchpoints_customer', 'touchpoint_records', ['customer_id', 'occurred_at'], unique=False)
    op.create_index('ix_touchpoints_visitor', 'touchpoint_records', ['visitor_id', 'occurred_at'], unique=False)
    op.create_table('attribution_results',
    sa.Column('revenue_event_id', sa.UUID(), nullable=False),
    sa.Column('touchpoint_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('attribution_model', sa.Enum('FIRST_TOUCH', 'LAST_TOUCH', 'LINEAR', 'TIME_DECAY', 'POSITION_BASED', 'DATA_DRIVEN', name='attributionmodel'), nullable=False),
    sa.Column('credit_percentage', sa.Float(), nullable=False),
    sa.Column('attributed_revenue', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revenue_event_id'], ['revenue_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['touchpoint_id'], ['touchpoint_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attribution_results')
    op.drop_index('ix_touchpoints_visitor', table_name='touchpoint_records')
    op.drop_index('ix_touchpoints_customer', table_name='touchpoint_records')
    op.drop_table('touchpoint_records')
    op.drop_index('ix_revenue_events_org_date', table_name='revenue_events')
    op.drop_table('revenue_events')
    op.drop_table('campaign_roi')
    op.drop_index('ix_channel_perf_org_period', table_name='channel_performance')
    op.drop_table('channel_performance')
    # ### end Alembic commands ###

