"""Add BehaviorMind models

Revision ID: 186e8294ef4f
Revises: 96c860b32dfd
Create Date: 2025-11-30 11:46:55.044329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '186e8294ef4f'
down_revision: Union[str, None] = '96c860b32dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversion_funnels',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_entries', sa.Integer(), nullable=False),
    sa.Column('total_completions', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_computed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heatmap_snapshots',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('page_path', sa.String(length=255), nullable=False),
    sa.Column('page_url', sa.String(length=500), nullable=False),
    sa.Column('heatmap_type', sa.String(length=20), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.Column('heatmap_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.DateTime(), nullable=False),
    sa.Column('date_to', sa.DateTime(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_heatmap_page_type', 'heatmap_snapshots', ['organization_id', 'page_path', 'heatmap_type'], unique=False)
    op.create_table('page_sessions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('page_url', sa.String(length=500), nullable=False),
    sa.Column('page_path', sa.String(length=255), nullable=False),
    sa.Column('page_title', sa.String(length=255), nullable=True),
    sa.Column('referrer_url', sa.String(length=500), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('browser_version', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.Column('screen_height', sa.Integer(), nullable=True),
    sa.Column('viewport_width', sa.Integer(), nullable=True),
    sa.Column('viewport_height', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('scroll_depth_max', sa.Integer(), nullable=False),
    sa.Column('clicks_count', sa.Integer(), nullable=False),
    sa.Column('mouse_moves_count', sa.Integer(), nullable=False),
    sa.Column('keystrokes_count', sa.Integer(), nullable=False),
    sa.Column('is_bounce', sa.Boolean(), nullable=False),
    sa.Column('had_rage_click', sa.Boolean(), nullable=False),
    sa.Column('had_dead_click', sa.Boolean(), nullable=False),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_page_sessions_org_path', 'page_sessions', ['organization_id', 'page_path'], unique=False)
    op.create_index(op.f('ix_page_sessions_page_path'), 'page_sessions', ['page_path'], unique=False)
    op.create_index(op.f('ix_page_sessions_session_id'), 'page_sessions', ['session_id'], unique=False)
    op.create_index('ix_page_sessions_started', 'page_sessions', ['organization_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_page_sessions_visitor_id'), 'page_sessions', ['visitor_id'], unique=False)
    op.create_table('click_events',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('page_x', sa.Integer(), nullable=False),
    sa.Column('page_y', sa.Integer(), nullable=False),
    sa.Column('element_tag', sa.String(length=50), nullable=True),
    sa.Column('element_class', sa.String(length=255), nullable=True),
    sa.Column('element_id', sa.String(length=100), nullable=True),
    sa.Column('element_text', sa.String(length=255), nullable=True),
    sa.Column('element_href', sa.String(length=500), nullable=True),
    sa.Column('click_type', sa.String(length=20), nullable=False),
    sa.Column('is_rage_click', sa.Boolean(), nullable=False),
    sa.Column('is_dead_click', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['page_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_interactions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.String(length=100), nullable=True),
    sa.Column('form_name', sa.String(length=255), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('field_label', sa.String(length=255), nullable=True),
    sa.Column('interaction_type', sa.String(length=20), nullable=False),
    sa.Column('time_spent_ms', sa.Integer(), nullable=False),
    sa.Column('was_filled', sa.Boolean(), nullable=False),
    sa.Column('was_changed', sa.Boolean(), nullable=False),
    sa.Column('was_cleared', sa.Boolean(), nullable=False),
    sa.Column('refill_count', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['page_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scroll_events',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('scroll_y', sa.Integer(), nullable=False),
    sa.Column('scroll_depth_percent', sa.Integer(), nullable=False),
    sa.Column('document_height', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['page_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scroll_events')
    op.drop_table('form_interactions')
    op.drop_table('click_events')
    op.drop_index(op.f('ix_page_sessions_visitor_id'), table_name='page_sessions')
    op.drop_index('ix_page_sessions_started', table_name='page_sessions')
    op.drop_index(op.f('ix_page_sessions_session_id'), table_name='page_sessions')
    op.drop_index(op.f('ix_page_sessions_page_path'), table_name='page_sessions')
    op.drop_index('ix_page_sessions_org_path', table_name='page_sessions')
    op.drop_table('page_sessions')
    op.drop_index('ix_heatmap_page_type', table_name='heatmap_snapshots')
    op.drop_table('heatmap_snapshots')
    op.drop_table('conversion_funnels')
    # ### end Alembic commands ###

