"""Add BrandVault models

Revision ID: 302a5d6bf411
Revises: 541b251aa4d4
Create Date: 2025-11-30 12:45:21.186145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '302a5d6bf411'
down_revision: Union[str, None] = '541b251aa4d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_folders',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('asset_count', sa.Integer(), nullable=False),
    sa.Column('subfolder_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['asset_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_folders_org_parent', 'asset_folders', ['organization_id', 'parent_id'], unique=False)
    op.create_table('asset_tags',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_tags_org_name', 'asset_tags', ['organization_id', 'name'], unique=True)
    op.create_table('assets',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('public_url', sa.String(length=500), nullable=True),
    sa.Column('cdn_url', sa.String(length=500), nullable=True),
    sa.Column('asset_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', 'TEMPLATE', 'LOGO', 'ICON', 'FONT', 'OTHER', name='assettype'), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('file_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exif_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('ai_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('previous_version_id', sa.UUID(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['asset_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_version_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_org_folder', 'assets', ['organization_id', 'folder_id'], unique=False)
    op.create_index('ix_assets_org_type', 'assets', ['organization_id', 'asset_type'], unique=False)
    op.create_table('asset_tag_mappings',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['asset_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'tag_id', 'id')
    )
    op.create_table('brand_guidelines',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('voice_tone', sa.Text(), nullable=True),
    sa.Column('primary_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secondary_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_font', sa.String(length=100), nullable=True),
    sa.Column('secondary_font', sa.String(length=100), nullable=True),
    sa.Column('font_guidelines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_logo_id', sa.UUID(), nullable=True),
    sa.Column('logo_usage_rules', sa.Text(), nullable=True),
    sa.Column('do_guidelines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dont_guidelines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_logo_id'], ['assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand_guidelines')
    op.drop_table('asset_tag_mappings')
    op.drop_index('ix_assets_org_type', table_name='assets')
    op.drop_index('ix_assets_org_folder', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_asset_tags_org_name', table_name='asset_tags')
    op.drop_table('asset_tags')
    op.drop_index('ix_folders_org_parent', table_name='asset_folders')
    op.drop_table('asset_folders')
    # ### end Alembic commands ###

