"""Add GlobalReach and ClientSync models

Revision ID: 33936971c914
Revises: 0ed3b7608d3e
Create Date: 2025-11-30 18:56:10.861246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33936971c914'
down_revision: Union[str, None] = '0ed3b7608d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_clients',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('client_organization_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_contact_name', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=True),
    sa.Column('contract_start_date', sa.DateTime(), nullable=True),
    sa.Column('contract_end_date', sa.DateTime(), nullable=True),
    sa.Column('monthly_retainer', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('can_access_billing', sa.Boolean(), nullable=False),
    sa.Column('can_access_analytics', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agency_clients_agency', 'agency_clients', ['agency_id'], unique=False)
    op.create_table('locale_settings',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('locale_code', sa.String(length=10), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('region_code', sa.String(length=5), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('native_name', sa.String(length=100), nullable=True),
    sa.Column('date_format', sa.String(length=50), nullable=False),
    sa.Column('time_format', sa.String(length=50), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('number_format', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_locale_settings_org_locale', 'locale_settings', ['organization_id', 'locale_code'], unique=True)
    op.create_table('translation_projects',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_language', sa.String(length=10), nullable=False),
    sa.Column('target_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('translated_items', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('white_label_configs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('logo_dark_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=False),
    sa.Column('secondary_color', sa.String(length=20), nullable=False),
    sa.Column('accent_color', sa.String(length=20), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('email_from_name', sa.String(length=255), nullable=True),
    sa.Column('email_from_address', sa.String(length=255), nullable=True),
    sa.Column('hidden_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('footer_text', sa.String(length=500), nullable=True),
    sa.Column('hide_powered_by', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('client_approvals',
    sa.Column('agency_client_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('item_title', sa.String(length=255), nullable=False),
    sa.Column('item_preview_url', sa.String(length=500), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_client_id'], ['agency_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_approvals_status', 'client_approvals', ['agency_client_id', 'status'], unique=False)
    op.create_table('client_reports',
    sa.Column('agency_client_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_client_id'], ['agency_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_items',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('item_key', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('context', sa.String(length=500), nullable=True),
    sa.Column('source_content', sa.Text(), nullable=False),
    sa.Column('source_language', sa.String(length=10), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['translation_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_translation_items_project_key', 'translation_items', ['project_id', 'item_key'], unique=False)
    op.create_table('translations',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('translated_content', sa.Text(), nullable=False),
    sa.Column('translation_method', sa.String(length=20), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['translation_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_translations_item_lang', 'translations', ['item_id', 'target_language'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_translations_item_lang', table_name='translations')
    op.drop_table('translations')
    op.drop_index('ix_translation_items_project_key', table_name='translation_items')
    op.drop_table('translation_items')
    op.drop_table('client_reports')
    op.drop_index('ix_client_approvals_status', table_name='client_approvals')
    op.drop_table('client_approvals')
    op.drop_table('white_label_configs')
    op.drop_table('translation_projects')
    op.drop_index('ix_locale_settings_org_locale', table_name='locale_settings')
    op.drop_table('locale_settings')
    op.drop_index('ix_agency_clients_agency', table_name='agency_clients')
    op.drop_table('agency_clients')
    # ### end Alembic commands ###

