"""Add RetentionAI models

Revision ID: 7fe85f575125
Revises: 186e8294ef4f
Create Date: 2025-11-30 12:02:34.189089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fe85f575125'
down_revision: Union[str, None] = '186e8294ef4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_programs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points_name', sa.String(length=50), nullable=False),
    sa.Column('points_per_dollar', sa.Float(), nullable=False),
    sa.Column('points_per_referral', sa.Integer(), nullable=False),
    sa.Column('points_per_review', sa.Integer(), nullable=False),
    sa.Column('tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rewards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('retention_campaigns',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='churnrisklevel'), nullable=False),
    sa.Column('trigger_min_score', sa.Integer(), nullable=False),
    sa.Column('trigger_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('email_subject', sa.String(length=255), nullable=True),
    sa.Column('email_template', sa.Text(), nullable=True),
    sa.Column('sms_template', sa.Text(), nullable=True),
    sa.Column('push_title', sa.String(length=100), nullable=True),
    sa.Column('push_body', sa.String(length=255), nullable=True),
    sa.Column('offer_type', sa.String(length=50), nullable=True),
    sa.Column('offer_value', sa.String(length=100), nullable=True),
    sa.Column('offer_code', sa.String(length=50), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('opened_count', sa.Integer(), nullable=False),
    sa.Column('clicked_count', sa.Integer(), nullable=False),
    sa.Column('converted_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_automated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('churn_predictions',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='churnrisklevel'), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('days_since_last_activity', sa.Integer(), nullable=True),
    sa.Column('days_since_last_purchase', sa.Integer(), nullable=True),
    sa.Column('engagement_trend', sa.String(length=20), nullable=True),
    sa.Column('support_tickets_recent', sa.Integer(), nullable=False),
    sa.Column('negative_feedback_count', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_churn_predictions_customer_id'), 'churn_predictions', ['customer_id'], unique=False)
    op.create_index('ix_churn_predictions_org_score', 'churn_predictions', ['organization_id', 'risk_score'], unique=False)
    op.create_table('customer_loyalty',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('total_points_earned', sa.Integer(), nullable=False),
    sa.Column('current_points', sa.Integer(), nullable=False),
    sa.Column('points_redeemed', sa.Integer(), nullable=False),
    sa.Column('current_tier', sa.String(length=50), nullable=False),
    sa.Column('tier_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_earned_at', sa.DateTime(), nullable=True),
    sa.Column('last_redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('referral_count', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['loyalty_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_table('retention_actions',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('content_subject', sa.String(length=255), nullable=True),
    sa.Column('content_preview', sa.String(length=500), nullable=True),
    sa.Column('offer_given', sa.String(length=100), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['retention_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loyalty_transactions',
    sa.Column('customer_loyalty_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_loyalty_id'], ['customer_loyalty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loyalty_transactions')
    op.drop_table('retention_actions')
    op.drop_table('customer_loyalty')
    op.drop_index('ix_churn_predictions_org_score', table_name='churn_predictions')
    op.drop_index(op.f('ix_churn_predictions_customer_id'), table_name='churn_predictions')
    op.drop_table('churn_predictions')
    op.drop_table('retention_campaigns')
    op.drop_table('loyalty_programs')
    # ### end Alembic commands ###

