"""Add CustomerDNA models

Revision ID: 96c860b32dfd
Revises: 572f4df10479
Create Date: 2025-11-30 11:36:09.539455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96c860b32dfd'
down_revision: Union[str, None] = '572f4df10479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_profiles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('age_range', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('location_country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('total_page_views', sa.Integer(), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('total_email_opens', sa.Integer(), nullable=False),
    sa.Column('total_email_clicks', sa.Integer(), nullable=False),
    sa.Column('total_ad_impressions', sa.Integer(), nullable=False),
    sa.Column('total_ad_clicks', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('average_order_value', sa.Float(), nullable=False),
    sa.Column('lifetime_value', sa.Float(), nullable=False),
    sa.Column('acquisition_source', sa.String(length=100), nullable=True),
    sa.Column('acquisition_campaign', sa.String(length=255), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=False),
    sa.Column('purchase_likelihood', sa.Integer(), nullable=False),
    sa.Column('churn_risk', sa.Integer(), nullable=False),
    sa.Column('customer_fit_score', sa.Integer(), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email_opt_in', sa.Boolean(), nullable=False),
    sa.Column('sms_opt_in', sa.Boolean(), nullable=False),
    sa.Column('push_opt_in', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_purchase_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_profiles_email'), 'customer_profiles', ['email'], unique=False)
    op.create_index('ix_customer_profiles_org_email', 'customer_profiles', ['organization_id', 'email'], unique=False)
    op.create_index('ix_customer_profiles_scores', 'customer_profiles', ['engagement_score', 'churn_risk'], unique=False)
    op.create_table('customer_segments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('segment_type', sa.String(length=50), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('last_computed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_dynamic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_events',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('campaign_id', sa.String(length=255), nullable=True),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('referrer_url', sa.String(length=500), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_events_customer_time', 'customer_events', ['customer_id', 'occurred_at'], unique=False)
    op.create_index('ix_customer_events_org_type', 'customer_events', ['organization_id', 'event_type'], unique=False)
    op.create_table('customer_journeys',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('awareness_at', sa.DateTime(), nullable=True),
    sa.Column('consideration_at', sa.DateTime(), nullable=True),
    sa.Column('evaluation_at', sa.DateTime(), nullable=True),
    sa.Column('purchase_at', sa.DateTime(), nullable=True),
    sa.Column('retention_at', sa.DateTime(), nullable=True),
    sa.Column('advocacy_at', sa.DateTime(), nullable=True),
    sa.Column('is_stalled', sa.Boolean(), nullable=False),
    sa.Column('stalled_days', sa.Integer(), nullable=False),
    sa.Column('velocity_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_journeys')
    op.drop_index('ix_customer_events_org_type', table_name='customer_events')
    op.drop_index('ix_customer_events_customer_time', table_name='customer_events')
    op.drop_table('customer_events')
    op.drop_table('customer_segments')
    op.drop_index('ix_customer_profiles_scores', table_name='customer_profiles')
    op.drop_index('ix_customer_profiles_org_email', table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_email'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    # ### end Alembic commands ###

