"""Add integration models for OAuth

Revision ID: b38877f2ea7b
Revises: 33936971c914
Create Date: 2025-11-30 20:49:39.132236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b38877f2ea7b'
down_revision: Union[str, None] = '33936971c914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('GOOGLE_ADS', 'META_ADS', 'LINKEDIN_ADS', 'TIKTOK_ADS', 'TWITTER_ADS', 'FACEBOOK', 'INSTAGRAM', 'TWITTER', 'LINKEDIN', 'TIKTOK', 'YOUTUBE', 'GOOGLE_ANALYTICS', 'SHOPIFY', 'WOOCOMMERCE', 'HUBSPOT', 'SALESFORCE', 'MAILCHIMP', 'SENDGRID', name='platformtype'), nullable=False),
    sa.Column('platform_account_id', sa.String(length=255), nullable=True),
    sa.Column('platform_account_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'EXPIRED', 'ERROR', 'PENDING', name='integrationstatus'), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('scopes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_by', sa.UUID(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refresh_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'platform', name='uq_org_platform')
    )
    op.create_index('ix_integration_expires', 'integration_tokens', ['expires_at'], unique=False)
    op.create_index('ix_integration_org_status', 'integration_tokens', ['organization_id', 'status'], unique=False)
    op.create_table('oauth_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('GOOGLE_ADS', 'META_ADS', 'LINKEDIN_ADS', 'TIKTOK_ADS', 'TWITTER_ADS', 'FACEBOOK', 'INSTAGRAM', 'TWITTER', 'LINKEDIN', 'TIKTOK', 'YOUTUBE', 'GOOGLE_ANALYTICS', 'SHOPIFY', 'WOOCOMMERCE', 'HUBSPOT', 'SALESFORCE', 'MAILCHIMP', 'SENDGRID', name='platformtype'), nullable=False),
    sa.Column('redirect_uri', sa.String(length=500), nullable=False),
    sa.Column('scopes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('code_verifier', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.create_index('ix_oauth_state_expires', 'oauth_states', ['expires_at'], unique=False)
    op.create_table('platform_webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('GOOGLE_ADS', 'META_ADS', 'LINKEDIN_ADS', 'TIKTOK_ADS', 'TWITTER_ADS', 'FACEBOOK', 'INSTAGRAM', 'TWITTER', 'LINKEDIN', 'TIKTOK', 'YOUTUBE', 'GOOGLE_ANALYTICS', 'SHOPIFY', 'WOOCOMMERCE', 'HUBSPOT', 'SALESFORCE', 'MAILCHIMP', 'SENDGRID', name='platformtype'), nullable=False),
    sa.Column('webhook_id', sa.String(length=255), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.Text(), nullable=True),
    sa.Column('events', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_webhooks')
    op.drop_index('ix_oauth_state_expires', table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index('ix_integration_org_status', table_name='integration_tokens')
    op.drop_index('ix_integration_expires', table_name='integration_tokens')
    op.drop_table('integration_tokens')
    # ### end Alembic commands ###

