"""Add ViralEngine models

Revision ID: e312d4772579
Revises: 7fe85f575125
Create Date: 2025-11-30 12:16:07.318832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e312d4772579'
down_revision: Union[str, None] = '7fe85f575125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('prize_name', sa.String(length=255), nullable=False),
    sa.Column('prize_description', sa.Text(), nullable=True),
    sa.Column('prize_value', sa.Float(), nullable=False),
    sa.Column('prize_image_url', sa.String(length=500), nullable=True),
    sa.Column('entry_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('winner_count', sa.Integer(), nullable=False),
    sa.Column('winner_selection', sa.String(length=50), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('total_entries', sa.Integer(), nullable=False),
    sa.Column('unique_participants', sa.Integer(), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamification_badges',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('criteria_type', sa.String(length=50), nullable=False),
    sa.Column('criteria_value', sa.Integer(), nullable=False),
    sa.Column('criteria_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('points_reward', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboards',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('show_top', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral_programs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('referrer_reward_type', sa.String(length=50), nullable=False),
    sa.Column('referrer_reward_value', sa.Float(), nullable=False),
    sa.Column('referrer_reward_description', sa.String(length=255), nullable=True),
    sa.Column('referred_reward_type', sa.String(length=50), nullable=False),
    sa.Column('referred_reward_value', sa.Float(), nullable=False),
    sa.Column('referred_reward_description', sa.String(length=255), nullable=True),
    sa.Column('min_purchase_amount', sa.Float(), nullable=False),
    sa.Column('max_referrals_per_user', sa.Integer(), nullable=False),
    sa.Column('reward_on_event', sa.String(length=50), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('total_referrals', sa.Integer(), nullable=False),
    sa.Column('successful_referrals', sa.Integer(), nullable=False),
    sa.Column('total_rewards_given', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ENDED', name='referralprogramstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contest_entries',
    sa.Column('contest_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('actions_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('winner_rank', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contest_entries_contest_email', 'contest_entries', ['contest_id', 'email'], unique=True)
    op.create_table('customer_badges',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['gamification_badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_badges_unique', 'customer_badges', ['customer_id', 'badge_id'], unique=True)
    op.create_table('referrals',
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('referrer_id', sa.UUID(), nullable=False),
    sa.Column('referred_id', sa.UUID(), nullable=True),
    sa.Column('referral_code', sa.String(length=50), nullable=False),
    sa.Column('referral_link', sa.String(length=500), nullable=False),
    sa.Column('referred_email', sa.String(length=255), nullable=True),
    sa.Column('referred_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('signed_up_at', sa.DateTime(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('referrer_rewarded', sa.Boolean(), nullable=False),
    sa.Column('referred_rewarded', sa.Boolean(), nullable=False),
    sa.Column('referrer_reward_amount', sa.Float(), nullable=False),
    sa.Column('referred_reward_amount', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['referral_programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referred_id'], ['customer_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referrer_id'], ['customer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_index('ix_referrals_code', 'referrals', ['referral_code'], unique=False)
    op.create_index('ix_referrals_referrer', 'referrals', ['referrer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_referrals_referrer', table_name='referrals')
    op.drop_index('ix_referrals_code', table_name='referrals')
    op.drop_table('referrals')
    op.drop_index('ix_customer_badges_unique', table_name='customer_badges')
    op.drop_table('customer_badges')
    op.drop_index('ix_contest_entries_contest_email', table_name='contest_entries')
    op.drop_table('contest_entries')
    op.drop_table('referral_programs')
    op.drop_table('leaderboards')
    op.drop_table('gamification_badges')
    op.drop_table('contests')
    # ### end Alembic commands ###

